/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetQuoteRouteRouteImport } from './routes/get-quote/route'
import { Route as ContractorRouteRouteImport } from './routes/contractor/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetQuoteIndexRouteImport } from './routes/get-quote/index'
import { Route as ContractorIndexRouteImport } from './routes/contractor/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as GetQuoteSignupRouteImport } from './routes/get-quote/signup'
import { Route as GetQuoteOnboardingRouteImport } from './routes/get-quote/onboarding'
import { Route as GetQuoteLoginRouteImport } from './routes/get-quote/login'
import { Route as ContractorWorkOrdersRouteImport } from './routes/contractor/work-orders'
import { Route as ContractorRoutesRouteImport } from './routes/contractor/routes'
import { Route as ContractorProfileRouteImport } from './routes/contractor/profile'
import { Route as ContractorDashboardRouteImport } from './routes/contractor/dashboard'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppOrdersRouteImport } from './routes/app/orders'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppQuotesIndexRouteImport } from './routes/app/quotes/index'
import { Route as AppPropertiesIndexRouteImport } from './routes/app/properties/index'
import { Route as AdminWorkOrdersIndexRouteImport } from './routes/admin/work-orders/index'
import { Route as AdminRoutesIndexRouteImport } from './routes/admin/routes/index'
import { Route as AdminQuotesIndexRouteImport } from './routes/admin/quotes/index'
import { Route as AdminPropertiesIndexRouteImport } from './routes/admin/properties/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminContractorsIndexRouteImport } from './routes/admin/contractors/index'
import { Route as AdminBillingIndexRouteImport } from './routes/admin/billing/index'
import { Route as ContractorStopsStopIdRouteImport } from './routes/contractor/stops/$stopId'
import { Route as AppQuotesQuoteIdRouteImport } from './routes/app/quotes/$quoteId'
import { Route as AppPropertiesPropertyIdRouteImport } from './routes/app/properties/$propertyId'
import { Route as AdminQuotesQuoteIdRouteImport } from './routes/admin/quotes/$quoteId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetQuoteRouteRoute = GetQuoteRouteRouteImport.update({
  id: '/get-quote',
  path: '/get-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorRouteRoute = ContractorRouteRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetQuoteIndexRoute = GetQuoteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GetQuoteRouteRoute,
} as any)
const ContractorIndexRoute = ContractorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GetQuoteSignupRoute = GetQuoteSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GetQuoteRouteRoute,
} as any)
const GetQuoteOnboardingRoute = GetQuoteOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => GetQuoteRouteRoute,
} as any)
const GetQuoteLoginRoute = GetQuoteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GetQuoteRouteRoute,
} as any)
const ContractorWorkOrdersRoute = ContractorWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorRoutesRoute = ContractorRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorProfileRoute = ContractorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorDashboardRoute = ContractorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminWorkOrdersIndexRoute = AdminWorkOrdersIndexRouteImport.update({
  id: '/work-orders/',
  path: '/work-orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoutesIndexRoute = AdminRoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuotesIndexRoute = AdminQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContractorsIndexRoute = AdminContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingIndexRoute = AdminBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ContractorStopsStopIdRoute = ContractorStopsStopIdRouteImport.update({
  id: '/stops/$stopId',
  path: '/stops/$stopId',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const AppQuotesQuoteIdRoute = AppQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPropertiesPropertyIdRoute = AppPropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminQuotesQuoteIdRoute = AdminQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/contractor': typeof ContractorRouteRouteWithChildren
  '/get-quote': typeof GetQuoteRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/contractor/dashboard': typeof ContractorDashboardRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/routes': typeof ContractorRoutesRoute
  '/contractor/work-orders': typeof ContractorWorkOrdersRoute
  '/get-quote/login': typeof GetQuoteLoginRoute
  '/get-quote/onboarding': typeof GetQuoteOnboardingRoute
  '/get-quote/signup': typeof GetQuoteSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/contractor/': typeof ContractorIndexRoute
  '/get-quote/': typeof GetQuoteIndexRoute
  '/admin/quotes/$quoteId': typeof AdminQuotesQuoteIdRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/app/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/contractor/stops/$stopId': typeof ContractorStopsStopIdRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
  '/admin/contractors/': typeof AdminContractorsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
  '/admin/routes/': typeof AdminRoutesIndexRoute
  '/admin/work-orders/': typeof AdminWorkOrdersIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/quotes/': typeof AppQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/contractor/dashboard': typeof ContractorDashboardRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/routes': typeof ContractorRoutesRoute
  '/contractor/work-orders': typeof ContractorWorkOrdersRoute
  '/get-quote/login': typeof GetQuoteLoginRoute
  '/get-quote/onboarding': typeof GetQuoteOnboardingRoute
  '/get-quote/signup': typeof GetQuoteSignupRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/contractor': typeof ContractorIndexRoute
  '/get-quote': typeof GetQuoteIndexRoute
  '/admin/quotes/$quoteId': typeof AdminQuotesQuoteIdRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/app/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/contractor/stops/$stopId': typeof ContractorStopsStopIdRoute
  '/admin/billing': typeof AdminBillingIndexRoute
  '/admin/contractors': typeof AdminContractorsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/properties': typeof AdminPropertiesIndexRoute
  '/admin/quotes': typeof AdminQuotesIndexRoute
  '/admin/routes': typeof AdminRoutesIndexRoute
  '/admin/work-orders': typeof AdminWorkOrdersIndexRoute
  '/app/properties': typeof AppPropertiesIndexRoute
  '/app/quotes': typeof AppQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/contractor': typeof ContractorRouteRouteWithChildren
  '/get-quote': typeof GetQuoteRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/contractor/dashboard': typeof ContractorDashboardRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/routes': typeof ContractorRoutesRoute
  '/contractor/work-orders': typeof ContractorWorkOrdersRoute
  '/get-quote/login': typeof GetQuoteLoginRoute
  '/get-quote/onboarding': typeof GetQuoteOnboardingRoute
  '/get-quote/signup': typeof GetQuoteSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/contractor/': typeof ContractorIndexRoute
  '/get-quote/': typeof GetQuoteIndexRoute
  '/admin/quotes/$quoteId': typeof AdminQuotesQuoteIdRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/app/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/contractor/stops/$stopId': typeof ContractorStopsStopIdRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
  '/admin/contractors/': typeof AdminContractorsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
  '/admin/routes/': typeof AdminRoutesIndexRoute
  '/admin/work-orders/': typeof AdminWorkOrdersIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/quotes/': typeof AppQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/contractor'
    | '/get-quote'
    | '/login'
    | '/app/dashboard'
    | '/app/orders'
    | '/app/payments'
    | '/app/profile'
    | '/contractor/dashboard'
    | '/contractor/profile'
    | '/contractor/routes'
    | '/contractor/work-orders'
    | '/get-quote/login'
    | '/get-quote/onboarding'
    | '/get-quote/signup'
    | '/admin/'
    | '/app/'
    | '/contractor/'
    | '/get-quote/'
    | '/admin/quotes/$quoteId'
    | '/app/properties/$propertyId'
    | '/app/quotes/$quoteId'
    | '/contractor/stops/$stopId'
    | '/admin/billing/'
    | '/admin/contractors/'
    | '/admin/customers/'
    | '/admin/properties/'
    | '/admin/quotes/'
    | '/admin/routes/'
    | '/admin/work-orders/'
    | '/app/properties/'
    | '/app/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/dashboard'
    | '/app/orders'
    | '/app/payments'
    | '/app/profile'
    | '/contractor/dashboard'
    | '/contractor/profile'
    | '/contractor/routes'
    | '/contractor/work-orders'
    | '/get-quote/login'
    | '/get-quote/onboarding'
    | '/get-quote/signup'
    | '/admin'
    | '/app'
    | '/contractor'
    | '/get-quote'
    | '/admin/quotes/$quoteId'
    | '/app/properties/$propertyId'
    | '/app/quotes/$quoteId'
    | '/contractor/stops/$stopId'
    | '/admin/billing'
    | '/admin/contractors'
    | '/admin/customers'
    | '/admin/properties'
    | '/admin/quotes'
    | '/admin/routes'
    | '/admin/work-orders'
    | '/app/properties'
    | '/app/quotes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/contractor'
    | '/get-quote'
    | '/login'
    | '/app/dashboard'
    | '/app/orders'
    | '/app/payments'
    | '/app/profile'
    | '/contractor/dashboard'
    | '/contractor/profile'
    | '/contractor/routes'
    | '/contractor/work-orders'
    | '/get-quote/login'
    | '/get-quote/onboarding'
    | '/get-quote/signup'
    | '/admin/'
    | '/app/'
    | '/contractor/'
    | '/get-quote/'
    | '/admin/quotes/$quoteId'
    | '/app/properties/$propertyId'
    | '/app/quotes/$quoteId'
    | '/contractor/stops/$stopId'
    | '/admin/billing/'
    | '/admin/contractors/'
    | '/admin/customers/'
    | '/admin/properties/'
    | '/admin/quotes/'
    | '/admin/routes/'
    | '/admin/work-orders/'
    | '/app/properties/'
    | '/app/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ContractorRouteRoute: typeof ContractorRouteRouteWithChildren
  GetQuoteRouteRoute: typeof GetQuoteRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-quote': {
      id: '/get-quote'
      path: '/get-quote'
      fullPath: '/get-quote'
      preLoaderRoute: typeof GetQuoteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor': {
      id: '/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof ContractorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-quote/': {
      id: '/get-quote/'
      path: '/'
      fullPath: '/get-quote/'
      preLoaderRoute: typeof GetQuoteIndexRouteImport
      parentRoute: typeof GetQuoteRouteRoute
    }
    '/contractor/': {
      id: '/contractor/'
      path: '/'
      fullPath: '/contractor/'
      preLoaderRoute: typeof ContractorIndexRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/get-quote/signup': {
      id: '/get-quote/signup'
      path: '/signup'
      fullPath: '/get-quote/signup'
      preLoaderRoute: typeof GetQuoteSignupRouteImport
      parentRoute: typeof GetQuoteRouteRoute
    }
    '/get-quote/onboarding': {
      id: '/get-quote/onboarding'
      path: '/onboarding'
      fullPath: '/get-quote/onboarding'
      preLoaderRoute: typeof GetQuoteOnboardingRouteImport
      parentRoute: typeof GetQuoteRouteRoute
    }
    '/get-quote/login': {
      id: '/get-quote/login'
      path: '/login'
      fullPath: '/get-quote/login'
      preLoaderRoute: typeof GetQuoteLoginRouteImport
      parentRoute: typeof GetQuoteRouteRoute
    }
    '/contractor/work-orders': {
      id: '/contractor/work-orders'
      path: '/work-orders'
      fullPath: '/contractor/work-orders'
      preLoaderRoute: typeof ContractorWorkOrdersRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/routes': {
      id: '/contractor/routes'
      path: '/routes'
      fullPath: '/contractor/routes'
      preLoaderRoute: typeof ContractorRoutesRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/profile': {
      id: '/contractor/profile'
      path: '/profile'
      fullPath: '/contractor/profile'
      preLoaderRoute: typeof ContractorProfileRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/dashboard': {
      id: '/contractor/dashboard'
      path: '/dashboard'
      fullPath: '/contractor/dashboard'
      preLoaderRoute: typeof ContractorDashboardRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/quotes/': {
      id: '/app/quotes/'
      path: '/quotes'
      fullPath: '/app/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/properties/': {
      id: '/app/properties/'
      path: '/properties'
      fullPath: '/app/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/work-orders/': {
      id: '/admin/work-orders/'
      path: '/work-orders'
      fullPath: '/admin/work-orders/'
      preLoaderRoute: typeof AdminWorkOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/routes/': {
      id: '/admin/routes/'
      path: '/routes'
      fullPath: '/admin/routes/'
      preLoaderRoute: typeof AdminRoutesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/quotes/': {
      id: '/admin/quotes/'
      path: '/quotes'
      fullPath: '/admin/quotes/'
      preLoaderRoute: typeof AdminQuotesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/properties/': {
      id: '/admin/properties/'
      path: '/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contractors/': {
      id: '/admin/contractors/'
      path: '/contractors'
      fullPath: '/admin/contractors/'
      preLoaderRoute: typeof AdminContractorsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing/': {
      id: '/admin/billing/'
      path: '/billing'
      fullPath: '/admin/billing/'
      preLoaderRoute: typeof AdminBillingIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/contractor/stops/$stopId': {
      id: '/contractor/stops/$stopId'
      path: '/stops/$stopId'
      fullPath: '/contractor/stops/$stopId'
      preLoaderRoute: typeof ContractorStopsStopIdRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/app/quotes/$quoteId': {
      id: '/app/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/app/quotes/$quoteId'
      preLoaderRoute: typeof AppQuotesQuoteIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/properties/$propertyId': {
      id: '/app/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/app/properties/$propertyId'
      preLoaderRoute: typeof AppPropertiesPropertyIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/quotes/$quoteId': {
      id: '/admin/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/admin/quotes/$quoteId'
      preLoaderRoute: typeof AdminQuotesQuoteIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminQuotesQuoteIdRoute: typeof AdminQuotesQuoteIdRoute
  AdminBillingIndexRoute: typeof AdminBillingIndexRoute
  AdminContractorsIndexRoute: typeof AdminContractorsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute
  AdminQuotesIndexRoute: typeof AdminQuotesIndexRoute
  AdminRoutesIndexRoute: typeof AdminRoutesIndexRoute
  AdminWorkOrdersIndexRoute: typeof AdminWorkOrdersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminQuotesQuoteIdRoute: AdminQuotesQuoteIdRoute,
  AdminBillingIndexRoute: AdminBillingIndexRoute,
  AdminContractorsIndexRoute: AdminContractorsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
  AdminQuotesIndexRoute: AdminQuotesIndexRoute,
  AdminRoutesIndexRoute: AdminRoutesIndexRoute,
  AdminWorkOrdersIndexRoute: AdminWorkOrdersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPropertiesPropertyIdRoute: typeof AppPropertiesPropertyIdRoute
  AppQuotesQuoteIdRoute: typeof AppQuotesQuoteIdRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppPropertiesPropertyIdRoute: AppPropertiesPropertyIdRoute,
  AppQuotesQuoteIdRoute: AppQuotesQuoteIdRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ContractorRouteRouteChildren {
  ContractorDashboardRoute: typeof ContractorDashboardRoute
  ContractorProfileRoute: typeof ContractorProfileRoute
  ContractorRoutesRoute: typeof ContractorRoutesRoute
  ContractorWorkOrdersRoute: typeof ContractorWorkOrdersRoute
  ContractorIndexRoute: typeof ContractorIndexRoute
  ContractorStopsStopIdRoute: typeof ContractorStopsStopIdRoute
}

const ContractorRouteRouteChildren: ContractorRouteRouteChildren = {
  ContractorDashboardRoute: ContractorDashboardRoute,
  ContractorProfileRoute: ContractorProfileRoute,
  ContractorRoutesRoute: ContractorRoutesRoute,
  ContractorWorkOrdersRoute: ContractorWorkOrdersRoute,
  ContractorIndexRoute: ContractorIndexRoute,
  ContractorStopsStopIdRoute: ContractorStopsStopIdRoute,
}

const ContractorRouteRouteWithChildren = ContractorRouteRoute._addFileChildren(
  ContractorRouteRouteChildren,
)

interface GetQuoteRouteRouteChildren {
  GetQuoteLoginRoute: typeof GetQuoteLoginRoute
  GetQuoteOnboardingRoute: typeof GetQuoteOnboardingRoute
  GetQuoteSignupRoute: typeof GetQuoteSignupRoute
  GetQuoteIndexRoute: typeof GetQuoteIndexRoute
}

const GetQuoteRouteRouteChildren: GetQuoteRouteRouteChildren = {
  GetQuoteLoginRoute: GetQuoteLoginRoute,
  GetQuoteOnboardingRoute: GetQuoteOnboardingRoute,
  GetQuoteSignupRoute: GetQuoteSignupRoute,
  GetQuoteIndexRoute: GetQuoteIndexRoute,
}

const GetQuoteRouteRouteWithChildren = GetQuoteRouteRoute._addFileChildren(
  GetQuoteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  ContractorRouteRoute: ContractorRouteRouteWithChildren,
  GetQuoteRouteRoute: GetQuoteRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
