/* eslint-disable unicorn/filename-case */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AdminBillingIndexRouteImport } from "./routes/admin/billing/index";
import { Route as AdminContractorsIndexRouteImport } from "./routes/admin/contractors/index";
import { Route as AdminCustomersCustomerRouteImport } from "./routes/admin/customers/$customer";
import { Route as AdminCustomersIndexRouteImport } from "./routes/admin/customers/index";
import { Route as AdminIndexRouteImport } from "./routes/admin/index";
import { Route as AdminPropertiesIndexRouteImport } from "./routes/admin/properties/index";
import { Route as AdminQuotesQuoteIdRouteImport } from "./routes/admin/quotes/$quoteId";
import { Route as AdminQuotesIndexRouteImport } from "./routes/admin/quotes/index";
import { Route as AdminRouteRouteImport } from "./routes/admin/route";
import { Route as AdminRoutesIndexRouteImport } from "./routes/admin/routes/index";
import { Route as AdminServicesIndexRouteImport } from "./routes/admin/services/index";
import { Route as AdminWorkOrdersIndexRouteImport } from "./routes/admin/work-orders/index";
import { Route as AppDashboardRouteImport } from "./routes/app/dashboard";
import { Route as AppIndexRouteImport } from "./routes/app/index";
import { Route as AppOrdersRouteImport } from "./routes/app/orders";
import { Route as AppPaymentsRouteImport } from "./routes/app/payments";
import { Route as AppProfileRouteImport } from "./routes/app/profile";
import { Route as AppPropertiesPropertyIdRouteImport } from "./routes/app/properties/$propertyId";
import { Route as AppPropertiesIndexRouteImport } from "./routes/app/properties/index";
import { Route as AppQuotesQuoteIdRouteImport } from "./routes/app/quotes/$quoteId";
import { Route as AppQuotesIndexRouteImport } from "./routes/app/quotes/index";
import { Route as AppRouteRouteImport } from "./routes/app/route";
import { Route as ContractorDashboardRouteImport } from "./routes/contractor/dashboard";
import { Route as ContractorIndexRouteImport } from "./routes/contractor/index";
import { Route as ContractorProfileRouteImport } from "./routes/contractor/profile";
import { Route as ContractorRouteRouteImport } from "./routes/contractor/route";
import { Route as ContractorRoutesRouteImport } from "./routes/contractor/routes";
import { Route as ContractorStopsStopIdRouteImport } from "./routes/contractor/stops/$stopId";
import { Route as ContractorWorkOrdersRouteImport } from "./routes/contractor/work-orders";
import { Route as GetQuoteIndexRouteImport } from "./routes/get-quote/index";
import { Route as GetQuoteLoginRouteImport } from "./routes/get-quote/login";
import { Route as GetQuoteOnboardingRouteImport } from "./routes/get-quote/onboarding";
import { Route as GetQuoteRouteRouteImport } from "./routes/get-quote/route";
import { Route as GetQuoteSignupRouteImport } from "./routes/get-quote/signup";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LoginRouteImport } from "./routes/login";

const LoginRoute = LoginRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/login",
  path: "/login",
} as any);
const GetQuoteRouteRoute = GetQuoteRouteRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/get-quote",
  path: "/get-quote",
} as any);
const ContractorRouteRoute = ContractorRouteRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/contractor",
  path: "/contractor",
} as any);
const AppRouteRoute = AppRouteRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/app",
  path: "/app",
} as any);
const AdminRouteRoute = AdminRouteRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/admin",
  path: "/admin",
} as any);
const IndexRoute = IndexRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/",
  path: "/",
} as any);
const GetQuoteIndexRoute = GetQuoteIndexRouteImport.update({
  getParentRoute: () => GetQuoteRouteRoute,
  id: "/",
  path: "/",
} as any);
const ContractorIndexRoute = ContractorIndexRouteImport.update({
  getParentRoute: () => ContractorRouteRoute,
  id: "/",
  path: "/",
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  getParentRoute: () => AppRouteRoute,
  id: "/",
  path: "/",
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/",
  path: "/",
} as any);
const GetQuoteSignupRoute = GetQuoteSignupRouteImport.update({
  getParentRoute: () => GetQuoteRouteRoute,
  id: "/signup",
  path: "/signup",
} as any);
const GetQuoteOnboardingRoute = GetQuoteOnboardingRouteImport.update({
  getParentRoute: () => GetQuoteRouteRoute,
  id: "/onboarding",
  path: "/onboarding",
} as any);
const GetQuoteLoginRoute = GetQuoteLoginRouteImport.update({
  getParentRoute: () => GetQuoteRouteRoute,
  id: "/login",
  path: "/login",
} as any);
const ContractorWorkOrdersRoute = ContractorWorkOrdersRouteImport.update({
  getParentRoute: () => ContractorRouteRoute,
  id: "/work-orders",
  path: "/work-orders",
} as any);
const ContractorRoutesRoute = ContractorRoutesRouteImport.update({
  getParentRoute: () => ContractorRouteRoute,
  id: "/routes",
  path: "/routes",
} as any);
const ContractorProfileRoute = ContractorProfileRouteImport.update({
  getParentRoute: () => ContractorRouteRoute,
  id: "/profile",
  path: "/profile",
} as any);
const ContractorDashboardRoute = ContractorDashboardRouteImport.update({
  getParentRoute: () => ContractorRouteRoute,
  id: "/dashboard",
  path: "/dashboard",
} as any);
const AppProfileRoute = AppProfileRouteImport.update({
  getParentRoute: () => AppRouteRoute,
  id: "/profile",
  path: "/profile",
} as any);
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  getParentRoute: () => AppRouteRoute,
  id: "/payments",
  path: "/payments",
} as any);
const AppOrdersRoute = AppOrdersRouteImport.update({
  getParentRoute: () => AppRouteRoute,
  id: "/orders",
  path: "/orders",
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
  getParentRoute: () => AppRouteRoute,
  id: "/dashboard",
  path: "/dashboard",
} as any);
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  getParentRoute: () => AppRouteRoute,
  id: "/quotes/",
  path: "/quotes/",
} as any);
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  getParentRoute: () => AppRouteRoute,
  id: "/properties/",
  path: "/properties/",
} as any);
const AdminWorkOrdersIndexRoute = AdminWorkOrdersIndexRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/work-orders/",
  path: "/work-orders/",
} as any);
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/services/",
  path: "/services/",
} as any);
const AdminRoutesIndexRoute = AdminRoutesIndexRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/routes/",
  path: "/routes/",
} as any);
const AdminQuotesIndexRoute = AdminQuotesIndexRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/quotes/",
  path: "/quotes/",
} as any);
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/properties/",
  path: "/properties/",
} as any);
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/customers/",
  path: "/customers/",
} as any);
const AdminContractorsIndexRoute = AdminContractorsIndexRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/contractors/",
  path: "/contractors/",
} as any);
const AdminBillingIndexRoute = AdminBillingIndexRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/billing/",
  path: "/billing/",
} as any);
const ContractorStopsStopIdRoute = ContractorStopsStopIdRouteImport.update({
  getParentRoute: () => ContractorRouteRoute,
  id: "/stops/$stopId",
  path: "/stops/$stopId",
} as any);
const AppQuotesQuoteIdRoute = AppQuotesQuoteIdRouteImport.update({
  getParentRoute: () => AppRouteRoute,
  id: "/quotes/$quoteId",
  path: "/quotes/$quoteId",
} as any);
const AppPropertiesPropertyIdRoute = AppPropertiesPropertyIdRouteImport.update({
  getParentRoute: () => AppRouteRoute,
  id: "/properties/$propertyId",
  path: "/properties/$propertyId",
} as any);
const AdminQuotesQuoteIdRoute = AdminQuotesQuoteIdRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/quotes/$quoteId",
  path: "/quotes/$quoteId",
} as any);
const AdminCustomersCustomerRoute = AdminCustomersCustomerRouteImport.update({
  getParentRoute: () => AdminRouteRoute,
  id: "/customers/$customer",
  path: "/customers/$customer",
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteRouteWithChildren;
  "/app": typeof AppRouteRouteWithChildren;
  "/contractor": typeof ContractorRouteRouteWithChildren;
  "/get-quote": typeof GetQuoteRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/app/dashboard": typeof AppDashboardRoute;
  "/app/orders": typeof AppOrdersRoute;
  "/app/payments": typeof AppPaymentsRoute;
  "/app/profile": typeof AppProfileRoute;
  "/contractor/dashboard": typeof ContractorDashboardRoute;
  "/contractor/profile": typeof ContractorProfileRoute;
  "/contractor/routes": typeof ContractorRoutesRoute;
  "/contractor/work-orders": typeof ContractorWorkOrdersRoute;
  "/get-quote/login": typeof GetQuoteLoginRoute;
  "/get-quote/onboarding": typeof GetQuoteOnboardingRoute;
  "/get-quote/signup": typeof GetQuoteSignupRoute;
  "/admin/": typeof AdminIndexRoute;
  "/app/": typeof AppIndexRoute;
  "/contractor/": typeof ContractorIndexRoute;
  "/get-quote/": typeof GetQuoteIndexRoute;
  "/admin/customers/$customer": typeof AdminCustomersCustomerRoute;
  "/admin/quotes/$quoteId": typeof AdminQuotesQuoteIdRoute;
  "/app/properties/$propertyId": typeof AppPropertiesPropertyIdRoute;
  "/app/quotes/$quoteId": typeof AppQuotesQuoteIdRoute;
  "/contractor/stops/$stopId": typeof ContractorStopsStopIdRoute;
  "/admin/billing/": typeof AdminBillingIndexRoute;
  "/admin/contractors/": typeof AdminContractorsIndexRoute;
  "/admin/customers/": typeof AdminCustomersIndexRoute;
  "/admin/properties/": typeof AdminPropertiesIndexRoute;
  "/admin/quotes/": typeof AdminQuotesIndexRoute;
  "/admin/routes/": typeof AdminRoutesIndexRoute;
  "/admin/services/": typeof AdminServicesIndexRoute;
  "/admin/work-orders/": typeof AdminWorkOrdersIndexRoute;
  "/app/properties/": typeof AppPropertiesIndexRoute;
  "/app/quotes/": typeof AppQuotesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/app/dashboard": typeof AppDashboardRoute;
  "/app/orders": typeof AppOrdersRoute;
  "/app/payments": typeof AppPaymentsRoute;
  "/app/profile": typeof AppProfileRoute;
  "/contractor/dashboard": typeof ContractorDashboardRoute;
  "/contractor/profile": typeof ContractorProfileRoute;
  "/contractor/routes": typeof ContractorRoutesRoute;
  "/contractor/work-orders": typeof ContractorWorkOrdersRoute;
  "/get-quote/login": typeof GetQuoteLoginRoute;
  "/get-quote/onboarding": typeof GetQuoteOnboardingRoute;
  "/get-quote/signup": typeof GetQuoteSignupRoute;
  "/admin": typeof AdminIndexRoute;
  "/app": typeof AppIndexRoute;
  "/contractor": typeof ContractorIndexRoute;
  "/get-quote": typeof GetQuoteIndexRoute;
  "/admin/customers/$customer": typeof AdminCustomersCustomerRoute;
  "/admin/quotes/$quoteId": typeof AdminQuotesQuoteIdRoute;
  "/app/properties/$propertyId": typeof AppPropertiesPropertyIdRoute;
  "/app/quotes/$quoteId": typeof AppQuotesQuoteIdRoute;
  "/contractor/stops/$stopId": typeof ContractorStopsStopIdRoute;
  "/admin/billing": typeof AdminBillingIndexRoute;
  "/admin/contractors": typeof AdminContractorsIndexRoute;
  "/admin/customers": typeof AdminCustomersIndexRoute;
  "/admin/properties": typeof AdminPropertiesIndexRoute;
  "/admin/quotes": typeof AdminQuotesIndexRoute;
  "/admin/routes": typeof AdminRoutesIndexRoute;
  "/admin/services": typeof AdminServicesIndexRoute;
  "/admin/work-orders": typeof AdminWorkOrdersIndexRoute;
  "/app/properties": typeof AppPropertiesIndexRoute;
  "/app/quotes": typeof AppQuotesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteRouteWithChildren;
  "/app": typeof AppRouteRouteWithChildren;
  "/contractor": typeof ContractorRouteRouteWithChildren;
  "/get-quote": typeof GetQuoteRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/app/dashboard": typeof AppDashboardRoute;
  "/app/orders": typeof AppOrdersRoute;
  "/app/payments": typeof AppPaymentsRoute;
  "/app/profile": typeof AppProfileRoute;
  "/contractor/dashboard": typeof ContractorDashboardRoute;
  "/contractor/profile": typeof ContractorProfileRoute;
  "/contractor/routes": typeof ContractorRoutesRoute;
  "/contractor/work-orders": typeof ContractorWorkOrdersRoute;
  "/get-quote/login": typeof GetQuoteLoginRoute;
  "/get-quote/onboarding": typeof GetQuoteOnboardingRoute;
  "/get-quote/signup": typeof GetQuoteSignupRoute;
  "/admin/": typeof AdminIndexRoute;
  "/app/": typeof AppIndexRoute;
  "/contractor/": typeof ContractorIndexRoute;
  "/get-quote/": typeof GetQuoteIndexRoute;
  "/admin/customers/$customer": typeof AdminCustomersCustomerRoute;
  "/admin/quotes/$quoteId": typeof AdminQuotesQuoteIdRoute;
  "/app/properties/$propertyId": typeof AppPropertiesPropertyIdRoute;
  "/app/quotes/$quoteId": typeof AppQuotesQuoteIdRoute;
  "/contractor/stops/$stopId": typeof ContractorStopsStopIdRoute;
  "/admin/billing/": typeof AdminBillingIndexRoute;
  "/admin/contractors/": typeof AdminContractorsIndexRoute;
  "/admin/customers/": typeof AdminCustomersIndexRoute;
  "/admin/properties/": typeof AdminPropertiesIndexRoute;
  "/admin/quotes/": typeof AdminQuotesIndexRoute;
  "/admin/routes/": typeof AdminRoutesIndexRoute;
  "/admin/services/": typeof AdminServicesIndexRoute;
  "/admin/work-orders/": typeof AdminWorkOrdersIndexRoute;
  "/app/properties/": typeof AppPropertiesIndexRoute;
  "/app/quotes/": typeof AppQuotesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/app"
    | "/contractor"
    | "/get-quote"
    | "/login"
    | "/app/dashboard"
    | "/app/orders"
    | "/app/payments"
    | "/app/profile"
    | "/contractor/dashboard"
    | "/contractor/profile"
    | "/contractor/routes"
    | "/contractor/work-orders"
    | "/get-quote/login"
    | "/get-quote/onboarding"
    | "/get-quote/signup"
    | "/admin/"
    | "/app/"
    | "/contractor/"
    | "/get-quote/"
    | "/admin/customers/$customer"
    | "/admin/quotes/$quoteId"
    | "/app/properties/$propertyId"
    | "/app/quotes/$quoteId"
    | "/contractor/stops/$stopId"
    | "/admin/billing/"
    | "/admin/contractors/"
    | "/admin/customers/"
    | "/admin/properties/"
    | "/admin/quotes/"
    | "/admin/routes/"
    | "/admin/services/"
    | "/admin/work-orders/"
    | "/app/properties/"
    | "/app/quotes/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/app/dashboard"
    | "/app/orders"
    | "/app/payments"
    | "/app/profile"
    | "/contractor/dashboard"
    | "/contractor/profile"
    | "/contractor/routes"
    | "/contractor/work-orders"
    | "/get-quote/login"
    | "/get-quote/onboarding"
    | "/get-quote/signup"
    | "/admin"
    | "/app"
    | "/contractor"
    | "/get-quote"
    | "/admin/customers/$customer"
    | "/admin/quotes/$quoteId"
    | "/app/properties/$propertyId"
    | "/app/quotes/$quoteId"
    | "/contractor/stops/$stopId"
    | "/admin/billing"
    | "/admin/contractors"
    | "/admin/customers"
    | "/admin/properties"
    | "/admin/quotes"
    | "/admin/routes"
    | "/admin/services"
    | "/admin/work-orders"
    | "/app/properties"
    | "/app/quotes";
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/app"
    | "/contractor"
    | "/get-quote"
    | "/login"
    | "/app/dashboard"
    | "/app/orders"
    | "/app/payments"
    | "/app/profile"
    | "/contractor/dashboard"
    | "/contractor/profile"
    | "/contractor/routes"
    | "/contractor/work-orders"
    | "/get-quote/login"
    | "/get-quote/onboarding"
    | "/get-quote/signup"
    | "/admin/"
    | "/app/"
    | "/contractor/"
    | "/get-quote/"
    | "/admin/customers/$customer"
    | "/admin/quotes/$quoteId"
    | "/app/properties/$propertyId"
    | "/app/quotes/$quoteId"
    | "/contractor/stops/$stopId"
    | "/admin/billing/"
    | "/admin/contractors/"
    | "/admin/customers/"
    | "/admin/properties/"
    | "/admin/quotes/"
    | "/admin/routes/"
    | "/admin/services/"
    | "/admin/work-orders/"
    | "/app/properties/"
    | "/app/quotes/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRouteRoute: typeof AdminRouteRouteWithChildren;
  AppRouteRoute: typeof AppRouteRouteWithChildren;
  ContractorRouteRoute: typeof ContractorRouteRouteWithChildren;
  GetQuoteRouteRoute: typeof GetQuoteRouteRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/get-quote": {
      id: "/get-quote";
      path: "/get-quote";
      fullPath: "/get-quote";
      preLoaderRoute: typeof GetQuoteRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contractor": {
      id: "/contractor";
      path: "/contractor";
      fullPath: "/contractor";
      preLoaderRoute: typeof ContractorRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/get-quote/": {
      id: "/get-quote/";
      path: "/";
      fullPath: "/get-quote/";
      preLoaderRoute: typeof GetQuoteIndexRouteImport;
      parentRoute: typeof GetQuoteRouteRoute;
    };
    "/contractor/": {
      id: "/contractor/";
      path: "/";
      fullPath: "/contractor/";
      preLoaderRoute: typeof ContractorIndexRouteImport;
      parentRoute: typeof ContractorRouteRoute;
    };
    "/app/": {
      id: "/app/";
      path: "/";
      fullPath: "/app/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/admin/": {
      id: "/admin/";
      path: "/";
      fullPath: "/admin/";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/get-quote/signup": {
      id: "/get-quote/signup";
      path: "/signup";
      fullPath: "/get-quote/signup";
      preLoaderRoute: typeof GetQuoteSignupRouteImport;
      parentRoute: typeof GetQuoteRouteRoute;
    };
    "/get-quote/onboarding": {
      id: "/get-quote/onboarding";
      path: "/onboarding";
      fullPath: "/get-quote/onboarding";
      preLoaderRoute: typeof GetQuoteOnboardingRouteImport;
      parentRoute: typeof GetQuoteRouteRoute;
    };
    "/get-quote/login": {
      id: "/get-quote/login";
      path: "/login";
      fullPath: "/get-quote/login";
      preLoaderRoute: typeof GetQuoteLoginRouteImport;
      parentRoute: typeof GetQuoteRouteRoute;
    };
    "/contractor/work-orders": {
      id: "/contractor/work-orders";
      path: "/work-orders";
      fullPath: "/contractor/work-orders";
      preLoaderRoute: typeof ContractorWorkOrdersRouteImport;
      parentRoute: typeof ContractorRouteRoute;
    };
    "/contractor/routes": {
      id: "/contractor/routes";
      path: "/routes";
      fullPath: "/contractor/routes";
      preLoaderRoute: typeof ContractorRoutesRouteImport;
      parentRoute: typeof ContractorRouteRoute;
    };
    "/contractor/profile": {
      id: "/contractor/profile";
      path: "/profile";
      fullPath: "/contractor/profile";
      preLoaderRoute: typeof ContractorProfileRouteImport;
      parentRoute: typeof ContractorRouteRoute;
    };
    "/contractor/dashboard": {
      id: "/contractor/dashboard";
      path: "/dashboard";
      fullPath: "/contractor/dashboard";
      preLoaderRoute: typeof ContractorDashboardRouteImport;
      parentRoute: typeof ContractorRouteRoute;
    };
    "/app/profile": {
      id: "/app/profile";
      path: "/profile";
      fullPath: "/app/profile";
      preLoaderRoute: typeof AppProfileRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/payments": {
      id: "/app/payments";
      path: "/payments";
      fullPath: "/app/payments";
      preLoaderRoute: typeof AppPaymentsRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/orders": {
      id: "/app/orders";
      path: "/orders";
      fullPath: "/app/orders";
      preLoaderRoute: typeof AppOrdersRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/dashboard": {
      id: "/app/dashboard";
      path: "/dashboard";
      fullPath: "/app/dashboard";
      preLoaderRoute: typeof AppDashboardRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/quotes/": {
      id: "/app/quotes/";
      path: "/quotes";
      fullPath: "/app/quotes/";
      preLoaderRoute: typeof AppQuotesIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/properties/": {
      id: "/app/properties/";
      path: "/properties";
      fullPath: "/app/properties/";
      preLoaderRoute: typeof AppPropertiesIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/admin/work-orders/": {
      id: "/admin/work-orders/";
      path: "/work-orders";
      fullPath: "/admin/work-orders/";
      preLoaderRoute: typeof AdminWorkOrdersIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/services/": {
      id: "/admin/services/";
      path: "/services";
      fullPath: "/admin/services/";
      preLoaderRoute: typeof AdminServicesIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/routes/": {
      id: "/admin/routes/";
      path: "/routes";
      fullPath: "/admin/routes/";
      preLoaderRoute: typeof AdminRoutesIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/quotes/": {
      id: "/admin/quotes/";
      path: "/quotes";
      fullPath: "/admin/quotes/";
      preLoaderRoute: typeof AdminQuotesIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/properties/": {
      id: "/admin/properties/";
      path: "/properties";
      fullPath: "/admin/properties/";
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/customers/": {
      id: "/admin/customers/";
      path: "/customers";
      fullPath: "/admin/customers/";
      preLoaderRoute: typeof AdminCustomersIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/contractors/": {
      id: "/admin/contractors/";
      path: "/contractors";
      fullPath: "/admin/contractors/";
      preLoaderRoute: typeof AdminContractorsIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/billing/": {
      id: "/admin/billing/";
      path: "/billing";
      fullPath: "/admin/billing/";
      preLoaderRoute: typeof AdminBillingIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/contractor/stops/$stopId": {
      id: "/contractor/stops/$stopId";
      path: "/stops/$stopId";
      fullPath: "/contractor/stops/$stopId";
      preLoaderRoute: typeof ContractorStopsStopIdRouteImport;
      parentRoute: typeof ContractorRouteRoute;
    };
    "/app/quotes/$quoteId": {
      id: "/app/quotes/$quoteId";
      path: "/quotes/$quoteId";
      fullPath: "/app/quotes/$quoteId";
      preLoaderRoute: typeof AppQuotesQuoteIdRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/properties/$propertyId": {
      id: "/app/properties/$propertyId";
      path: "/properties/$propertyId";
      fullPath: "/app/properties/$propertyId";
      preLoaderRoute: typeof AppPropertiesPropertyIdRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/admin/quotes/$quoteId": {
      id: "/admin/quotes/$quoteId";
      path: "/quotes/$quoteId";
      fullPath: "/admin/quotes/$quoteId";
      preLoaderRoute: typeof AdminQuotesQuoteIdRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/admin/customers/$customer": {
      id: "/admin/customers/$customer";
      path: "/customers/$customer";
      fullPath: "/admin/customers/$customer";
      preLoaderRoute: typeof AdminCustomersCustomerRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute;
  AdminCustomersCustomerRoute: typeof AdminCustomersCustomerRoute;
  AdminQuotesQuoteIdRoute: typeof AdminQuotesQuoteIdRoute;
  AdminBillingIndexRoute: typeof AdminBillingIndexRoute;
  AdminContractorsIndexRoute: typeof AdminContractorsIndexRoute;
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute;
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute;
  AdminQuotesIndexRoute: typeof AdminQuotesIndexRoute;
  AdminRoutesIndexRoute: typeof AdminRoutesIndexRoute;
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute;
  AdminWorkOrdersIndexRoute: typeof AdminWorkOrdersIndexRoute;
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBillingIndexRoute: AdminBillingIndexRoute,
  AdminContractorsIndexRoute: AdminContractorsIndexRoute,
  AdminCustomersCustomerRoute: AdminCustomersCustomerRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
  AdminQuotesIndexRoute: AdminQuotesIndexRoute,
  AdminQuotesQuoteIdRoute: AdminQuotesQuoteIdRoute,
  AdminRoutesIndexRoute: AdminRoutesIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminWorkOrdersIndexRoute: AdminWorkOrdersIndexRoute,
};

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren
);

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute;
  AppOrdersRoute: typeof AppOrdersRoute;
  AppPaymentsRoute: typeof AppPaymentsRoute;
  AppProfileRoute: typeof AppProfileRoute;
  AppIndexRoute: typeof AppIndexRoute;
  AppPropertiesPropertyIdRoute: typeof AppPropertiesPropertyIdRoute;
  AppQuotesQuoteIdRoute: typeof AppQuotesQuoteIdRoute;
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute;
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
  AppPropertiesPropertyIdRoute: AppPropertiesPropertyIdRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppQuotesQuoteIdRoute: AppQuotesQuoteIdRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren
);

interface ContractorRouteRouteChildren {
  ContractorDashboardRoute: typeof ContractorDashboardRoute;
  ContractorProfileRoute: typeof ContractorProfileRoute;
  ContractorRoutesRoute: typeof ContractorRoutesRoute;
  ContractorWorkOrdersRoute: typeof ContractorWorkOrdersRoute;
  ContractorIndexRoute: typeof ContractorIndexRoute;
  ContractorStopsStopIdRoute: typeof ContractorStopsStopIdRoute;
}

const ContractorRouteRouteChildren: ContractorRouteRouteChildren = {
  ContractorDashboardRoute: ContractorDashboardRoute,
  ContractorIndexRoute: ContractorIndexRoute,
  ContractorProfileRoute: ContractorProfileRoute,
  ContractorRoutesRoute: ContractorRoutesRoute,
  ContractorStopsStopIdRoute: ContractorStopsStopIdRoute,
  ContractorWorkOrdersRoute: ContractorWorkOrdersRoute,
};

const ContractorRouteRouteWithChildren = ContractorRouteRoute._addFileChildren(
  ContractorRouteRouteChildren
);

interface GetQuoteRouteRouteChildren {
  GetQuoteLoginRoute: typeof GetQuoteLoginRoute;
  GetQuoteOnboardingRoute: typeof GetQuoteOnboardingRoute;
  GetQuoteSignupRoute: typeof GetQuoteSignupRoute;
  GetQuoteIndexRoute: typeof GetQuoteIndexRoute;
}

const GetQuoteRouteRouteChildren: GetQuoteRouteRouteChildren = {
  GetQuoteIndexRoute: GetQuoteIndexRoute,
  GetQuoteLoginRoute: GetQuoteLoginRoute,
  GetQuoteOnboardingRoute: GetQuoteOnboardingRoute,
  GetQuoteSignupRoute: GetQuoteSignupRoute,
};

const GetQuoteRouteRouteWithChildren = GetQuoteRouteRoute._addFileChildren(
  GetQuoteRouteRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  ContractorRouteRoute: ContractorRouteRouteWithChildren,
  GetQuoteRouteRoute: GetQuoteRouteRouteWithChildren,
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";

import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
